// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpvPUYkGCu-6abU-1dhu4znCYSK1sfHA',
    appId: '1:588796688014:web:eb7eb50afc1dd5217a7bdf',
    messagingSenderId: '588796688014',
    projectId: 'metro-user-data',
    authDomain: 'metro-user-data.firebaseapp.com',
    storageBucket: 'metro-user-data.firebasestorage.app',
    measurementId: 'G-L7MY4XPFKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZ_Nu3pEd95UvFE9gtgb-pj0Lh4Gp9dE',
    appId: '1:588796688014:android:b62568e8416165e67a7bdf',
    messagingSenderId: '588796688014',
    projectId: 'metro-user-data',
    storageBucket: 'metro-user-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgxA-xVU53uDaPPTkhEq2RjzlcKaSahY',
    appId: '1:588796688014:ios:fb6101554620b0ea7a7bdf',
    messagingSenderId: '588796688014',
    projectId: 'metro-user-data',
    storageBucket: 'metro-user-data.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgxA-xVU53uDaPPTkhEq2RjzlcKaSahY',
    appId: '1:588796688014:ios:fb6101554620b0ea7a7bdf',
    messagingSenderId: '588796688014',
    projectId: 'metro-user-data',
    storageBucket: 'metro-user-data.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIpvPUYkGCu-6abU-1dhu4znCYSK1sfHA',
    appId: '1:588796688014:web:a03610ed63d0bc377a7bdf',
    messagingSenderId: '588796688014',
    projectId: 'metro-user-data',
    authDomain: 'metro-user-data.firebaseapp.com',
    storageBucket: 'metro-user-data.firebasestorage.app',
    measurementId: 'G-SQN04TM1JV',
  );
}
